CREATE TABLE IF NOT EXISTS pt_forms (
  id INT AUTO_INCREMENT PRIMARY KEY,
  member_id INT,
  user_id INT,
  form_data JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (member_id) REFERENCES gym_members(id) ON DELETE CASCADE
);
